Library/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('books/', include('books.urls')),
    path('', include('django.contrib.auth.urls')),
]

books/urls.py
from django.contrib.auth import views as auth_views
from django.urls import path
from books.views import IndexView, CreateStudent, DeleteStudent, \
                        UpdateStudent, DetailStudent, CreateBooks


app_name = 'books'
urlpatterns = [
    path('', IndexView.as_view(), name='index'),
    path('new_student/', CreateStudent.as_view(), name='create_students'),
    path('delete/<pk>/', DeleteStudent.as_view(), name='delete_student'),
    path('login/', auth_views.LoginView.as_view(), name='login'),
    path('logout/', auth_views.LogoutView.as_view(), name='logout'),
    path('update_student/<pk>/',
         UpdateStudent.as_view(), name='update_student'),
    path('detail_student/<pk>/',
         DetailStudent.as_view(), name='detail_student'),
    path('create_books/', CreateBooks.as_view(), name='create_books'),
]

books/models.py
from django.db import models


class Category(models.Model):
    name = models.CharField(max_length=50, unique=True)
    created_at = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return self.name

    class Meta:
        verbose_name = 'Categoria'


class Books(models.Model):
    name = models.CharField(max_length=100)
    created_at = models.DateTimeField(auto_now_add=True)
    category = models.ForeignKey(
        Category, on_delete=models.CASCADE, related_name='category')

    def __str__(self):
        return self.name

    class Meta:
        verbose_name = 'Livro'


class Student(models.Model):
    name = models.CharField(max_length=70)
    cpf = models.CharField(max_length=14)
    birth_date = models.DateField()
    city = models.CharField(max_length=50)
    registration_date = models.DateTimeField(auto_now_add=True)
    email = models.EmailField(max_length=50)
    tel = models.CharField(max_length=15)
    book= models.ForeignKey(
        Books, on_delete=models.CASCADE, related_name='book')

    class Meta:
        verbose_name = 'Estudante'
        ordering = ['-id']

    def __str__(self):
        return self.name

books/forms.py
from django.forms import ModelForm, TextInput, Select, DateInput
from .models import Student, Books

# Form de criação de livros.


class FormBooks(ModelForm):
    class Meta:
        model = Books
        fields = ['name', 'category']

        widgets = {
            'name': TextInput(attrs={'class': 'form-control', 'placeholder': 'Digite o nome da categoria'}),
            'category': Select(attrs={'class': 'form-control'}),
        }

# Form cadastro de aluguel de livros.


class FormStudent(ModelForm):

    class Meta:
        model = Student
        fields = ['name', 'cpf', 'birth_date',
                  'city', 'email', 'tel', 'book']

        widgets = {
            'name': TextInput(attrs={'class': 'form-control', 'placeholder': 'Digite seu nome'}),
            'cpf': TextInput(attrs={'class': 'form-control', 'placeholder': 'Digite seu CPF'}),
            'birth_date': DateInput(attrs={'type': 'date', 'class': 'form-control'}),
            'city': TextInput(attrs={'class': 'form-control', 'placeholder': 'Digite sua cidade'}),
            'email': TextInput(attrs={'class': 'form-control', 'placeholder': 'Digite seu e-mail'}),
            'tel': TextInput(attrs={'class': 'form-control', 'placeholder': 'Digite seu telefone'}),
            'book': Select(attrs={'class': 'form-control'}),

        }

# Form Upgrade cadastro estudante.


class UpdateForm(ModelForm):
    class Meta:
        model = Student
        fields = ['email', 'tel', 'book']

        widgets = {
            'book': Select(attrs={'class': 'form-control'}),
        }

books/views.py
from django.urls import reverse_lazy
from django.views import generic
from django.shortcuts import get_object_or_404
from django.core.paginator import Paginator
from .forms import FormStudent, UpdateForm, FormBooks
from django.contrib.auth.mixins import LoginRequiredMixin
from django.contrib.messages.views import SuccessMessageMixin
from books.models import Student, Category, Books
from datetime import date, timedelta


class IndexView(LoginRequiredMixin, generic.ListView):

    template_name = 'books/index.html'
    context_object_name = 'contacts'
    paginate_by = 4
    model = Student
    login_url = '/login/'
    

    def get_queryset(self):

        query = self.request.GET.get('search')
        students = Student.objects.all()

        if query:
            students = students.filter(name__icontains=query)
        return students


class DeleteStudent(LoginRequiredMixin, SuccessMessageMixin, generic.DeleteView):
    template_name = 'books/delete.html'
    model = Student
    context_object_name = 'student'
    success_url = reverse_lazy('books:index')
    login_url = '/login/'
    success_message = 'Estudante excluido com sucesso'



class UpdateStudent(LoginRequiredMixin, SuccessMessageMixin, generic.UpdateView):
    template_name = 'books/update_student.html'
    model = Student
    form_class = UpdateForm
    success_url = reverse_lazy('books:index')
    success_message = 'Atualizado com sucesso'
    login_url = '/login/'


class CreateStudent(LoginRequiredMixin, SuccessMessageMixin, generic.CreateView):
    template_name = 'books/create_student.html'
    model = Student
    form_class = FormStudent
    success_url = reverse_lazy('books:index')
    success_message = 'Cadastrado com sucesso'
    login_url = '/login/'


class CreateBooks(LoginRequiredMixin, SuccessMessageMixin, generic.CreateView):
    template_name = 'books/create_books.html'
    model = Books
    form_class = FormBooks
    success_url = reverse_lazy('books:index')
    success_message = 'Livro cadastrado com sucesso'
    login_url = '/login/'


class DetailStudent(LoginRequiredMixin, generic.DetailView):
    template_name = 'books/detail_student.html'
    model = Student
    login_url = '/login/'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['now'] = date.today()
        context['date'] = get_object_or_404(Student, pk=self.kwargs['pk'])
        context['birth_of_date'] = context['date'].birth_date
        context['year'] = timedelta(days=365)
        context['result'] = int(
            abs((context['birth_of_date'] - context['now']) / context['year']))
        return context

books/templates/books/base.html
<!DOCTYPE html>
<html lang="pt-br">
{% load static %}

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <link href="{% static 'css/bootstrap.min.css' %}" rel="stylesheet">
    <link href="{% static 'css/estilo.css' %}" rel="stylesheet">
    <script type="text/javascript" src="{% static 'js/bootstrap.min.js' %}"></script>
    <script type="text/javascript" src="{% static 'js/jquery.min.js' %}"></script>
 
 
    <title>{% block title %} {% endblock%} </title>

</head>

<body>


    <nav class="navbar navbar-expand-lg navbar-dark bg-dark">
        <div class="container">
            {% if not user.is_authenticated%}
            <a class="navbar-brand" href="{% url 'login' %}">Sistema de Aluno</a>

            {% else %}
            <div class="collapse navbar-collapse" id="navbarSupportedContent">
                <ul class="navbar-nav mr-auto">
                    <li class="nav-item active">
                        <span class="nav-link">User: {{ user.username|capfirst }}</span>

                    </li>

                    <li class="nav-item active">
                        <a href="{% url 'books:index' %}" class="nav-link">Home</a>
                    </li>

                </ul>

                <ul class="navbar-nav mr-left">
                    <li class="nav-item active">
                        {% if user.is_authenticated %}
                        <a href="{% url 'books:create_books' %}" title="Cadastrar Livros" style="margin-right: 10px;"
                            class="btn btn-success linkar"><i class="fas fa-plus-circle"></i> Livro</a>
                        <a href="{% url 'books:create_students' %}" title="Cadastrar Estudante" style="margin-right: 10px;"
                            class="btn btn-info linkar"><i class="fas fa-plus-circle"></i> Estudante</a>
                        <a href="{% url 'books:logout' %}" title="Sair" class="btn btn-danger linkar"><i
                                class="fas fa-sign-out-alt"></i> Logout</a>
                        {% endif %}
                    </li>
                </ul><br />
            </div>
            {% endif %}
            <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent"
                aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>
        </div>
    </nav>



    <br />

    <div class="container" style="margin-top: -17px;">
        <div class="text-center">
            <h1 style="color: white;">Biblioteca</h1>
            <br />
        </div> <!-- Fim page-header -->

        {% block content %}

        {% endblock %}

    </div> <!-- Fim container -->


    <script type="text/javascript"
        src="https://cdnjs.cloudflare.com/ajax/libs/jquery.mask/1.14.10/jquery.mask.js"></script>
    <script type="text/javascript" src='https://kit.fontawesome.com/e3e4fb1593.js' crossorigin='anonymous'></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.3/umd/popper.min.js"
        integrity="sha384-vFJXuSJphROIrBnz7yo7oB41mKfc8JzQZiCq4NCceLEaO4IHwicKwpJf9c9IpFgh"
        crossorigin="anonymous"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0-beta.2/js/bootstrap.min.js"
        integrity="sha384-alpBpkh1PFOepccYVYDB4do5UnbKysX5WZXm3XxPqe5iKTfUKjNkCk9SaVuEZflJ"
        crossorigin="anonymous"></script>

</body>

</html>

books/templates/books/create_books.html
{% extends 'books/base.html' %}

{% block title %}Cadastro de Categoria{% endblock %}

{% block content %}

<form method="post">
    {% csrf_token %}
    <div class="form-group">
        <label for="{{ form.name.id_for_label }}">Nome do livro</label>
        {{form.name}}
    </div>


    <div class="form-group">
            <label for="{{ form.category.id_for_label }}">Nome da Categoria</label>
            {{ form.category }}
        </div>

    <a href="{% url 'books:index' %}" class="btn btn-danger">Voltar</a>
    <button class="btn btn-dark linkar">Cadastrar</button>
</form>


{% endblock %}

books/templates/books/create_student.html
{% extends 'books/base.html' %}

{% block title %}Cadastrar Estudante{% endblock %}

{% block content %}


<script type="text/javascript">
    $(document).ready(function () {
        $("#id_cpf").mask("000.000.000-00");
    });

    $(document).ready(function () {
        $("#id_tel").mask("(00) 00000-0000");
    });

</script>

<div class="row">
    <div class="col-lg-12 col-md-12 col-sm-12 col-xs-12">
        <div class="card">
            <div class="card-body" id="cor-fundo">
                <h5 class="card-title"><i class="fas fa-plus-square"></i> Cadastro</h5>
                <p class="card-text">
                    <form method="POST">
                        {% csrf_token %}
                        <div class="form-group">

                            <label for="{{ form.name.id_for_label }}">Nome do Estudante</label>
                            {{ form.name }}
                            <br />

                            <label for="{{ form.cpf.id_for_label }}">Cpf</label>
                            {{ form.cpf }}
                            <br />

                            <label for="{{ form.birth_date.id_for_label }}">Data de Nascimento</label>
                            {{ form.birth_date }}

                            <br />

                            <label for="{{ form.city.id_for_label }}">Cidade</label>
                            {{ form.city }}
                            <br />

                            <label for="{{ form.email.id_for_label }}">E-mail</label>
                            {{ form.email }}
                            <br />

                            <label for="{{ form.tel.id_for_label }}">Telefone</label>
                            {{ form.tel }}
                            <br />

                            <label for="{{ form.book.id_for_label }}">Livros Disponíveis</label>
                            {{ form.book }}
                            <br />


                            <a href="{% url 'books:index' %}" class="btn btn-danger linkar">Voltar</a>
                            <button class="btn btn-dark linkar">Cadastrar</button>

                        </div>
                    </form>
                </p>
            </div>
        </div>




        {% endblock %}

books/templates/books/delete.html
{% extends 'books/base.html' %}

{% block title %}Excluir {{ student.name|title }}{% endblock %}

{% block content %}
<style>
    .alert-heading {
        font-size: 65px;
    }

    p {
        font-size: 19px;
    }
</style>


<form method="post">
    {% csrf_token %}


    <div class="row">
        <div class="col-lg-12 col-md-12 col-sm-12 col-xs-12">
            <div class="card text-center">
                <div class="card-body" id="cor-fundo">
                    <h5 class="card-title">
                        <h4 class="alert-heading">Atenção</h4>
                        <p class="card-text">

                            <p>Você tem certeza que deseja excluir o estudante <strong>{{ student.name|title }}
                                    ?</strong></p>
                            <hr>
                            <a class="btn btn-dark linkar" href="{% url 'books:index' %}"><i
                                    class="fas fa-arrow-circle-left"></i> Cancelar</a>

                            <button style="margin: 10px;" class="btn btn-danger linkar"><i class="fas fa-trash"></i>
                                Excluir</button>
                            <p>
                                <p class="mb-0">Após exclusão, não será possível recuperar os dados.</p>
                            </p>
                </div>
            
            </div>
</form>



{% endblock %}

books/templates/books/detail_student.html
{% extends 'books/base.html' %}

{% block title %}Detalhes do Estudante {{ student.name }}{% endblock %}

{% block content %}

<div class="container">
    <div class="row">
        <div class="col-lg-12 col-md-12 col-sm-12 col-xs-12">
            <div class="card">
                <div class="card-body" id="cor-fundo">
                    <h5 class="card-title"><i class="fas fa-user"></i> {{ student.name|title }}</h5>
                    <p class="card-text">
                        ID: <code>{{ student.id }}</code><br />
                        Livro Alugado: <code>{{ student.book|title }}</code><br />
                        Nascido em: <code>{{ student.birth_date }}</code><br />
                        Idade: <code>{{ result }} Anos</code><br />
                        E-mail: <code>{{ student.email}}</code><br />
                        Telefone: <code>{{ student.tel}}</code><br />
                        Cidade: <code>{{ student.city}}</code><br />
                    </p>
                </div>
                <a href="{% url 'books:index' %}" class="btn btn-danger linkar" title="Voltar">Voltar</a>
            </div>
        </div>
{% endblock %}

books/templates/books/index.html
{% extends 'books/base.html' %}

{% block title %}Home {% endblock %}

{% block content %}

{% if contacts %}

{% if messages %}
<div class="alert alert-warning">
    {% for message in messages %}
    {{ message }}
    {% endfor %}
</div>
{% endif %}

<nav class="navbar navbar-expand-sm bg-dark navbar-dark" style="margin-bottom:10px;">
    <form method="GET" class="form-inline">
        <input class="form-control mr-sm-2" name="search" type="text" placeholder="Pesquisar"
            value="{{ request.GET.search }}">
        <button class="btn btn-success" title="Pesquisar" type="submit"><i class="fas fa-search"></i> Pesquisar</button>
    </form>
</nav>

<div class="row">
    {% for exibir in contacts %}
    <div class="col-lg-6 col-md-6 col-sm-6 col-xs-12">
        <div class="card">
            <div class="card-body">
                <h5 class="card-title"><i class="fas fa-user"></i> {{ exibir.name }}</h5>
                <p class="card-text">
                    Livro Alugado: <code>{{ exibir.book|title }}</code>.
                </p>

                <a class="btn btn-info" title="Informações" href="{% url 'books:detail_student' exibir.id %}"><i
                        class="fas fa-eye"></i></a>
                <a class="btn btn-warning" title="Atualizar" href="{% url 'books:update_student' exibir.id %}"><i
                        class="far fa-edit"></i></a>

                <a class="btn btn-danger" title="Deletar" href="{% url 'books:delete_student' exibir.id %}"><i
                        class="fas fa-trash"></i></a>

            </div>

        </div><br />
    </div>

    {% endfor %}
</div>


<!-- Paginação  -->
{% if is_paginated %}
<nav aria-label="Page navigation example">
    <ul class="pagination">

        {% if page_obj.has_previous %}

        <li class="page-item">
            <a class="page-link" href="?page={{ page_obj.previous_page_number }}" aria-label="Previous">
                <span aria-hidden="true">&laquo;</span>
            </a>

        </li> <!-- Fim do page-item 1 (Previous) -->
        {% endif %}

        {% if page_obj.has_next %}

        <li class="page-item">
            <a class="page-link" href="?page={{ page_obj.number }}">{{ page_obj.number }}</a>
        </li>

        <li class="page-item">
            <a class="page-link" href="?page={{ page_obj.paginator.num_pages }}">{{ page_obj.paginator.num_pages }}</a>
        </li>

        <li class="page-item">
            <a class="page-link" href="?page={{ page_obj.next_page_number }}" aria-label="Next">
                <span aria-hidden="true">&raquo;</span>
            </a>
        </li>
        {% endif %}
    </ul>
</nav>

{% endif %}

{# Caso não tenha itens cadastrados #}
{% else %}
<div class="alert alert-light text-center" role="alert">
    <h4 class="alert-heading">Lista Vazia Ou Item não localizado</h4>

    <p>Nenhum estudante foi localizado no sistema, caso queira cadastrar livros alugados clique no link abaixo
    </p>
    <hr>
    <a class="btn btn-info" href="{% url 'books:create_students' %}" role="button">Link Aqui</a>
</div>

{% endif %}
{% endblock %}

books/templates/books/update_student.html
{% extends 'books/base.html' %}

{% block title %}Atualizar Estudante{% endblock %}


{% block content %}


<script type="text/javascript">
    $(document).ready(function () {
        $("#id_tel").mask("(00) 00000-0000");
    });

</script>

    <div class="row">
        <div class="col-lg-12 col-md-12 col-sm-12 col-xs-12">
            <div class="card">
                <div class="card-body" id="cor-fundo">
                    <h5 class="card-title"><i class="fas fa-user"></i> {{ student.name|title }}</h5>
                    <p class="card-text">
                        <form method="POST">
                                {% csrf_token %}
                            <div class="form-group">
                                <label for="{{ form.email.id_for_label }}">E-mail</label>
                                <input type="text" class="form-control" id="id_email" name="email"
                                    value="{{ student.email }}">
                                <br />

                                <label for="{{ form.tel.id_for_label }}">Telefone</label>
                                <input type="text" class="form-control" id="id_tel" name="tel"
                                    value="{{ student.tel }}">
                                <br />

                                <label for="{{ form.book.id_for_label }}">Livro Alugado</label>
                                {{ form.book }}
                                <br />


                                <a href="{% url 'books:index' %}" class="btn btn-danger linkar">Voltar</a>
                                <button class="btn btn-dark linkar">Atualizar</button>

                            </div>
                        </form>
                    </p>
                </div>
            </div>
   

        {% endblock %}